services:
  backend:
    build:
      context: ./backend
      dockerfile: ./.docker/Dockerfile.dev
    volumes:
      - ./backend:/home/node/app:cached
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image:  redis:8.2.2-alpine
    container_name: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  frontend:
    build:
      context: ./frontend
      dockerfile: ./.docker/Dockerfile.dev
    volumes:
      - ./frontend:/home/node/app:cached
    ports:
      - "4200:4200"
